# fly.toml app configuration file generated for aurametropolis on 2026-05-13

app = "aurametropolis"
primary_region = "jnb" # Johannesburg is the closest region to Mauritius on Fly.io

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
